<a href="https://colab.research.google.com/github/dhruviladani/ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
a = np.array([1,2,3])
print (type(a), a.shape, a[0], a[1], a[2])
a[0]=5
print (a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[3,4,5]])
print (type(a), a.shape, a[0], a[1], a[2])

<class 'numpy.ndarray'> (3,) 5 2 3


In [ ]:
a = np.zeros((2,2))
print (a)


[[0. 0.]
 [0. 0.]]


In [ ]:
c = np.full((2,2),7)
print (c)

[[7 7]
 [7 7]]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]
print (b)

[[2 3]
 [6 7]]


In [ ]:
print (a)

[[11  2  3  4]
 [ 5  6 17  8]
 [19 10 11 12]]


In [ ]:
print (a[0,1])


2


In [ ]:
b = np.array([0,2,0])
print(b)

[0 2 0]


In [ ]:
a.shape

(3, 4)

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
a[np.arange(3), b] += 10
print (a)


[[11  2  3  4]
 [ 5  6 17  8]
 [19 10 11 12]]


In [ ]:
bool_idx = (a>2)
print(bool_idx)

[[ True False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
print(a[bool_idx])
print(a[a>2])

[11  3  4  5  6 17  8 19 10 11 12]
[11  3  4  5  6 17  8 19 10 11 12]


In [ ]:
x = np.array([1,2])
y = np.arary([1.0,2.0])
z = np.array([1,2], dtype=np.int64)

print(x.dtype , y.dtype, z.dtype )

AttributeError: ignored

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[1,2]])
print(a+b)

[[4 6]
 [4 6]]


In [ ]:
print(np.add(a,b))

[[4 6]
 [4 6]]


In [ ]:
print(np.subtract(a,b))

[[-2 -2]
 [ 2  2]]


In [ ]:
print(np.multiply(a,b))

[[3 8]
 [3 8]]


In [ ]:
print(np.divide(a,b))

[[0.33333333 0.5       ]
 [3.         2.        ]]


In [ ]:
print(np.sqrt(a))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
print(a.dot(b))
print(a @ b)

[[ 5  8]
 [13 20]]
[[ 5  8]
 [13 20]]


In [ ]:
print(a)
print("transpose\n",a.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]
